name: tcp
version: 0.0.1

includes:
  modules:
    library:
      at: !File main.ospl
      require: []

    binary:
      at: !File tests.ospl
      require: []

  packages: {}

requires: {}

extensions:
  tcpExtension:
    file: "extension.c"
